imports:
  - { resource: services.yaml }

services:
  App\Gateway\EmployeeGateway: '@App\Adapter\Doctrine\Repository\EmployeeRepository'
  App\Gateway\ContactGateway: '@App\Adapter\Doctrine\Repository\ContactRepository'
  App\Gateway\UserGateway: '@App\Adapter\Doctrine\Repository\UserRepository'
  App\Gateway\PosGateway: '@App\Adapter\Doctrine\Repository\PosRepository'
  App\Gateway\TankGateway: '@App\Adapter\Doctrine\Repository\TankRepository'
  App\Gateway\PumpGateway: '@App\Adapter\Doctrine\Repository\PumpRepository'
  App\Gateway\TypeProductGateway: '@App\Adapter\Doctrine\Repository\TypeProductRepository'
  App\Gateway\ProductFamilyGateway: '@App\Adapter\Doctrine\Repository\ProductFamilyRepository'
  App\Gateway\ProductGateway: '@App\Adapter\Doctrine\Repository\ProductRepository'

