imports:
  - { resource: services.yaml }

services:
  App\Gateway\EmployeeGateway: '@App\Adapter\Doctrine\Repository\EmployeeRepository'
  App\Gateway\ContactGateway: '@App\Adapter\Doctrine\Repository\ContactRepository'