pos:
  path:     /
  controller: App\Controller\PosController::index

pos.new:
  path:     /new
  controller: App\Controller\PosController::new

pos.create:
  path: /create
  controller: App\Controller\PosController::create
  requirements: { _method: post }

pos.show:
  path: /{id}/show
  controller: App\Controller\PosController::show

pos.edit:
  path:     /{id}/edit
  controller: App\Controller\PosController::edit

pos.update:
  path: /{id}/update
  controller: App\Controller\PosController::update
  requirements: { _method: post|put }

pos.activate:
  path: /{id}/activate
  controller: App\Controller\PosController::activate
  requirements: { _method: post|put }

pos.disable:
  path: /{id}/disable
  controller: App\Controller\PosController::disable
  requirements: { _method: post|put }

pos.validate:
  path: /{id}/validate
  controller: App\Controller\PosController::validate
  requirements: { _method: post|put }

pos.invalidate:
  path: /{id}/invalidate
  controller: App\Controller\PosController::invalidate
  requirements: { _method: post|put }