tank:
  path:     /
  controller: App\Controller\TankController::index

tank.new:
  path:     /{pos}/new
  controller: App\Controller\TankController::new

tank.create:
  path: /{pos}/create
  controller: App\Controller\TankController::create
  requirements: { _method: post }

tank.show:
  path: /{id}
  controller: App\Controller\TankController::show

tank.edit:
  path:     /{id}/edit
  controller: App\Controller\TankController::edit

tank.update:
  path: /{id}/update
  controller: App\Controller\TankController::update
  requirements: { _method: post|put }

tank.activate:
  path: /{id}/activate
  controller: App\Controller\TankController::activate
  requirements: { _method: post|put }

tank.disable:
  path: /{id}/disable
  controller: App\Controller\TankController::disable
  requirements: { _method: post|put }

tank.validate:
  path: /{id}/validate
  controller: App\Controller\TankController::validate
  requirements: { _method: post|put }

tank.invalidate:
  path: /{id}/invalidate
  controller: App\Controller\TankController::invalidate
  requirements: { _method: post|put }