tank.new:
  path:     /{pos}/new
  controller: App\Controller\TankController::new

tank.create:
  path: /{pos}/create
  controller: App\Controller\TankController::create
  requirements: { _method: post }

tank.show:
  path: /{id}/show
  controller: App\Controller\TankController::show