# This is a basic workflow to help you get started with Actions

name: Continuous Integration

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
jobs:
  router:
    name: Gestion de stations services
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.4']    
